In [1]:
println("I am excited to learn Julia")

I am excited to learn Julia


In [2]:
my_name="Daksh"
typeof(my_name)

String

In [3]:
#Single line comment
#=
multiple line comment
=#

In [1]:
modulus = 101%2

1

In [2]:
my_name = "Daksh"
my_digits= 10
my_toes= 10


10

In [4]:
println("My name is $my_name. I have $my_digits fingers and $my_toes toes")

My name is Daksh. I have 10 fingers and 10 toes


String Concatenation

In [6]:
string("How many cats are ","too many cats?")

"How many cats are too many cats?"

In [8]:
s3 = "How many cats"
s4 = " are too many?"

s3*s4

"How many cats are too many?"

In [9]:
"$s3$s4"

"How many cats are too many?"

Dictionaries

In [10]:
myphonebook = Dict("Daksh"=>"9810-216-489","Shreya"=>"7303-129-555")

Dict{String, String} with 2 entries:
  "Daksh"  => "9810-216-489"
  "Shreya" => "7303-129-555"

In [12]:
myphonebook["Papa"]="9868-717-272"

"9868-717-272"

In [13]:
myphonebook

Dict{String, String} with 3 entries:
  "Daksh"  => "9810-216-489"
  "Shreya" => "7303-129-555"
  "Papa"   => "9868-717-272"

to delete an entry

In [14]:
pop!(myphonebook,"Daksh")

"9810-216-489"

In [15]:
myphonebook

Dict{String, String} with 2 entries:
  "Shreya" => "7303-129-555"
  "Papa"   => "9868-717-272"

Tuple - Can be indexed

In [16]:
myfavoriteanimals = ("Shreya","Cats","monkeys")

("Shreya", "Cats", "monkeys")

In [17]:
myfavoriteanimals[1]

"Shreya"

but tuples are immutable -> We can't update it

Array

In [18]:
fibonacci =[1,1,2,3,5,8,13]

7-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13

In [19]:
push!(fibonacci,21)

8-element Vector{Int64}:
  1
  1
  2
  3
  5
  8
 13
 21

In [21]:
pop!(fibonacci)

21

Loops

while & for loops

In [28]:
n=0
while n<10
    n+=1
    println(n)
end


1
2
3
4
5
6
7
8
9
10


In [27]:
myfriend = ["Ted","Robyn","Barney","Marshal","Lily"]
i=1
while i<=length(myfriend)
    friend = myfriend[i]
    println("Hi $friend, it is great to see you.")
    i+=1
end

Hi Ted, it is great to see you.
Hi Robyn, it is great to see you.
Hi Barney, it is great to see you.
Hi Marshal, it is great to see you.
Hi Lily, it is great to see you.


For Loops

In [29]:
for friend in myfriend
    println("Hi $friend, it is great to see you")
end

Hi Ted, it is great to see you
Hi Robyn, it is great to see you
Hi Barney, it is great to see you
Hi Marshal, it is great to see you
Hi Lily, it is great to see you


Create a new table using for loop

In [31]:
m,n = 5,5
A = zeros(m,n)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [32]:
for i in 1:m,j in 1:n
    A[i,j] = i+j
end
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

The Julia way

In [33]:
C = [i+j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

Conditionals

The julia way

In [37]:
x = 90
y = 60

(x>y) ? x : y

90

Shortcuts

In [38]:
(x>y) && ("$x is greater than $y")

"90 is greater than 60"

In [40]:
(x<y) && ("$x is lesser than $y")

false

Functions

How to declare a function ?

In [41]:
function sayhi(name)
    println("Hi $name")
end

sayhi (generic function with 1 method)

In [43]:
sayhi("Julia")

Hi Julia

In [44]:
sayhi(name) = println("Hi $name")
sayhi("Sheru")

Hi Sheru


In [46]:
sayhi3 = name -> println("Hi $name")
sayhi3("Sheru ki Mumma")

Hi Sheru ki Mumma


Duck typing in Julia